### ISSUE TITLE
Dead links in the readme.md

### ISSUE THREAD

**Issue by ghost** [mdditt2000/openshift-3-11#4]
https://github.com/mdditt2000/openshift-4-7/blob/master/README.md

Standalone BIGIP [document](https://github.com/mdditt2000/openshift-3-11/blob/master/enviroment/standalone/big-ip-83/QuickStartGuide.md)
    High Availability BIGIP [document](https://github.com/mdditt2000/openshift-3-11/blob/master/enviroment/high-availability/bigip%20ha%20deployment/ha-deployment-guide.md)
    AS3 Override Examples [document](https://github.com/mdditt2000/openshift-3-11/blob/master/examples/as3-override/QuickStartGuide.md)
    OpenShift CIS FAQ [document](https://github.com/mdditt2000/openshift-3-11/blob/master/openshift-faq.md)

**Comment by mdditt2000** [comment]
@TonyMarfil please use the following link https://github.com/mdditt2000/k8s-bigip-ctlr/blob/main/user_guides/README.md

What documents are you looking for?

**Comment by mdditt2000** [comment]
Updated links https://github.com/mdditt2000/openshift-4-7
